### ISSUE TITLE
.dbd file missing

### ISSUE THREAD

**Issue by sivanandareddy** [prjemian/cmd_response#1]
Is it necessary to have dbd file? If i would like to edit with VDCT (visual Database Configuration Tool) is it possible?

**Comment by prjemian** [comment]
Only if you wish to use VDCT.  Then you need a .dbd file.
I rely on the default .dbd that comes from EPICS base:
/usr/local/epics/base/src/std/softIoc/base.dbd

```
# This file includes the standard record types and device support
# provided by Base and (usually) loaded into all IOCs.
```

It is not necessary to include this file file in the cmd_response project.
